tutorial/tutorial/post/urls.py
from django.urls import path
from .views import PostTopListView,PostCreateFormView,PostSearchView,PostDetailView,PostClaimView,PostUpdateView,PostDeleteView

app_name = 'post'

urlpatterns = [
    path('', PostTopListView.as_view(),name='post_top'),
    path('create/',PostCreateFormView.as_view(),name='post_create'),
    path('search/',PostSearchView.as_view(),name='post_search'),
    path('detail/<int:pk>',PostDetailView.as_view(),name='post_detail'),
    path('claim/',PostClaimView.as_view(),name='post_claim'),
    path('update/<int:pk>',PostUpdateView.as_view(),name='post_update'),
    path('delete/<int:pk>',PostDeleteView.as_view(),name='post_delete'),
]

tutorial/tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls')),
]

tutorial/tutorial/post/models.py
from django.db import models

class Post(models.Model):
    name = models.CharField('投稿者',max_length=100)
    naiyou = models.TextField('投稿内容',max_length=250)


    def __str__(self):
        return self.name

tutorial/tutorial/post/forms.py
from django import forms
from .models import Post

class ClaimForm(forms.Form):
    name = forms.CharField(label='なまえ',max_length=100)
    email = forms.EmailField(label='メールアドレス')
    text = forms.CharField(label='クレーム内容', widget=forms.Textarea)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('name','naiyou')

tutorial/tutorial/post/views.py
from .models import Post
from django.views.generic import ListView,CreateView,TemplateView,FormView,DetailView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .forms import ClaimForm, PostForm
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.shortcuts import redirect
from django.urls import reverse
from django.db.models import Q

"""
トップページ
"""
class PostTopListView(ListView):
    model = Post
    paginate_by = 5

"""
詳細画面
"""
class PostDetailView(DetailView):
    model = Post
    template_name = 'post/post_detail.html'

"""
編集
"""
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'post/post_create_form.html'
    success_url = reverse_lazy('post:post_top')

"""
削除
"""
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('post:post_top')
    
"""
投稿ページ
"""
class PostCreateFormView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post/post_create_form.html'
    success_url = reverse_lazy('post:post_top')

""" 
検索フォーム
"""
class PostSearchView(ListView):
    model = Post
    paginate_by = 5
    template_name = 'post/post_search_form.html'

    def get_queryset(self):
        queryset = Post.objects.all()
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(Q(name__icontains=keyword) | Q(naiyou__icontains=keyword))
        return queryset

"""
クレーム欄
"""
class PostClaimView(FormView):
    form_class = ClaimForm
    success_url = reverse_lazy('post:post_top')
    template_name = 'post/post_form.html'

    def form_valid(self, form):
        subject = 'クレームが入りました。'
        message = render_to_string('mail/mail.txt',form.cleaned_data,self.request)
        from_email = 'shoutaro0726@gmail.com' #任意のメールアドレス
        recipient_list = ['shoutaro0726@gmail.com'] #任意のメールアドレス
        send_mail(subject, message, from_email, recipient_list)
        return redirect('post:post_top')
    





    

tutorial/tutorial/post/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>ぽすと</title>
</head>
<body>
    <header>
        <h1 class="head-top"><a class="head-top-link" href="{% url 'post:post_top' %}">ぽすと</a></h1>
    
        <ul class="nav-list">
            <li class="navs"><a class="tops" href="{% url 'post:post_create' %}">投稿してみる</a></li>
            <li class="navs"><a class="tops" href="{% url 'post:post_claim' %}">クレーム</a></li>
        </ul>
    </header>

{% block content %}{% endblock %}


</body>
</html>

tutorial/tutorial/post/templates/pagination.html
<div class="pager">
    <ul class="pagination">
        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
                <li><a href="?page={{ page_num }}" class="active"><span>{{ page_num }}</span></a></li>
            {% else %}
                <li><a href="?page={{ page_num }}" ><span>{{ page_num }}</span></a></li>
            {% endif %}
        {% endfor%}
            {% if page_obj.has_next %}
                <li class="next"><a href="?page={{ page_obj.next_page_number }}"><span>»</span></a></li>
            {% endif %}
    </ul>
</div>

tutorial/tutorial/post/templates/post/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<header class="sub-headers">削除しますがよろしいでしょうか？</header>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <div class="btn-center">
        <button class="btn" type="submit">削除</button>
        <a class="back" href="{% url 'post:post_detail' post.pk %}">戻る</a>
    </div>    
</form>
{% endblock %}

tutorial/tutorial/post/templates/post/post_create_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<header class="sub-headers">投稿してみる / 編集</header>
<section class="post-form">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="submit">投稿する</button>
    </form>
</section>
{% endblock %}

tutorial/tutorial/post/templates/post/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<header class="sub-headers">投稿詳細</header>

<a href="{% url 'post:post_update' post.pk %}" class="btn-border">編集</a>
<a href="{% url 'post:post_delete' post.pk %}" class="btn-border2">削除</a>

<div class="toko">
        <h4 style="color: red;">{{ post.name }}</h4>
        <p>{{ post.naiyou }}</p>
</div>

{% endblock %}

tutorial/tutorial/post/templates/post/post_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<header class="sub-headers">クレーム</header>
<section class="post-form">
    <form action="" method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit" class="submit">送信</button>
    </form>
</section>
{% endblock %}

tutorial/tutorial/post/templates/post/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<header class="sub-headers">投稿一覧</header>
{% include "search.html" %}

{% for post in post_list %}
<div class="toko">
    <a class="detail-link" href="{% url 'post:post_detail' post.pk %}">
    <h4 style="color: red;">{{ post.name }}</h4>
    <p>{{ post.naiyou }}</p>
    </a>
</div>
{% endfor %}

{% include "pagination.html" %}

<div id="page_top"><a href="#"></a></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>

{% endblock %}
    

tutorial/tutorial/post/templates/post/post_search_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<header class="sub-headers">検索結果</header>

{% for post in post_list %}
<div class="toko">
    <a class="detail-link" href="#">
        <h4>{{ post.name }}</h4>
        <p>{{ post.naiyou }}</p>
    </a>
</div>
{% endfor %}

{% include "pagination.html" %}

{% endblock %}

tutorial/tutorial/post/templates/search.html
<form method="get" action="{% url 'post:post_search'  %}" class="search_container">
    <input type="text" size="30" placeholder="検索" name="keyword">
    <input type="submit" value="&#xf002">
</form>